name: CI for Pull Requests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  Build_Stateless_solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore packages
      run: dotnet restore
      
    - name: Build Stateless solution
      run: dotnet build UnicornHatHdDotnet --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release
      
    - name: Build package
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: dotnet pack src/UnicornHatHdDotnet/UnicornHatHdDotnet.csproj --configuration Release

    # - name: Publish package
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: dotnet nuget push src/UnicornHatHdDotnet/bin/Release/*.nupkg -s nuget.org --api-key ${{ secrets.NUGETAPIKEY }}
