name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        fetch-depth: 0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Get new version tag
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        change_path: "src/UnicornHatHdDotnet"

    - name: Show new version tag
      run: echo ${{ steps.version.outputs.version }}

    - name: Package
      if: steps.version.outputs.version != ''
      run: dotnet pack src/UnicornHatHdDotnet/UnicornHatHdDotnet.csproj -c Release -o package -p:PackageVersion=${{ steps.version.outputs.version }}
