name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Show version number
      shell: pwsh
      run: |
           $version = "${{ github.event.release.tag_name }}".TrimStart('v')
           "package_version=$version" >> $env:GITHUB_ENV

    - name: Log version
      run: echo ${{ env.package_version }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Dotnet pack
      run: dotnet pack src/UnicornHatHdDotnet/UnicornHatHdDotnet.csproj -c Release -o package -p:PackageVersion=${{ env.package_version }}

    #- name: NuGet push
    #  run: dotnet nuget push ./package/*.nupkg -s nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
