name: Release

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Show version number
      shell: pwsh
      run: |
           $version = "${{ github.event.release.tag_name }}".TrimStart('v')
           "package_version=$version" >> $env:GITHUB_ENV

    - name: Log version
      run: echo ${{ env.package_version }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet test --verbosity normal

    - name: Dotnet pack
      run: dotnet pack src/UnicornHatHdDotnet/UnicornHatHdDotnet.csproj -c Release -o package -p:PackageVersion=${{ env.package_version }}

    - uses: actions/upload-artifact@v3
      with:
        name: package
        path: package/*
    
    - name: NuGet push
      run: dotnet nuget push ./package/*.nupkg -s nuget.org --api-key ${{ secrets.NUGET_API_KEY }}
